name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug step to confirm directory structure
      - name: List directory contents
        run: ls -alh && ls crudproject/

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r crudproject/requirements.txt

  docker:
    runs-on: ubuntu-latest #
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app1:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app1:latest


      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: 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
    
    
      - name: Build and push to GHCR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/siroj003/django-app1:latest

  notify:
    runs-on: ubuntu-latest
    needs: [docker]

    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -1002092401069
          token: 7198702423:AAFrDqMlsKVoFZmaTU1RxRDeJOns8LJ6rP4
          message: |
           ${{ github.actor }} created commit:
           Commit message: Hello World
         
           Repository: ${{ github.repository }}
        
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}