name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug step to confirm directory structure
      - name: List directory contents
        run: ls -alh && ls crudproject/

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r crudproject/requirements.txt

  docker:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: siroj9656
          password: Siroj123@

      - name: Build and push Docker image
        run: |
          docker build -t siroj9656/django-app1:latest .
          docker push siroj9656/django-app1:latest

      - name : Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: Siroj003
          password: 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

  notify:
    runs-on: ubuntu-latest
    needs: [docker]

    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 7405961898
          token: AAH73WZ0kSKP9lUYEo48PQxOVb_BR79jdHw
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
          
            Repository: ${{ github.repository }}
          
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}